### ISSUE TITLE
Problems with default user parameter in manifest/params.pp.

### ISSUE THREAD

**Issue by gwarf** [cern-it-sdc-id/puppet-dmlite#11]
HI,
We are installing a dpm head+disk node and we do encounter some troubles with the rights on ```/etc/dmlite.conf``` and /etc/dmlite* files: they belong to *root* instead of *dpmmgr*.
In ```manifests/params.pp``` the defaults for user and group are taken first in hiera and if not from ```lcgdm::base::config::user```. We did not put ```dmlite::params::user``` and ```dmlite::params::group``` in hera and at least at this time of the run it seems that  ```$lcgdm::base::config::user``` is returning nothing, as shown by a ```notify {$user: }``` added to the params.pp class.
It is a bit uncommon to have a module that gets some of its default from another module.
If I set ```dmlite::params::user: 'dpmmgr'``` in hiera it works but it looks a bit abnormal to have to do this as we want to use the defaut parameter.
We did base our puppet code on the example available and are running with puppet 4.3.2.
Am I missing something? Would it be possible to set dpmmgr as a fallback value for user and group parameters directly in ```manifests/params.pp```?
Thanks!

**Comment by andrea-manzi** [comment]
Hello,
yes i think you are totally right, we should add a default parameter for the user param, cause in any case it would be dpmmgr in 99 % of the cases. 
Anyway i don't see this problem in my testbeds, ( they are running puppet 3.8.x) , could be that this issue only affects puppet 4?
thanks
Andrea

**Comment by gwarf** [comment]
Yep it is possible and I seems very likely to be the case but I didn't had the opportunity to do more thoroughfull tests, it could aslo be a side effect on how I did adapt the examples (even if am doubtful about this), I am not sure, but setting a local default parameter won't cause problems to puppet 3.x and it seems cleaner.
I've got a dpm working on SL6 and configured with puppet 4 and this was the last thing causing troubles, so by the way thanks for all the works on those modules!

**Comment by andrea-manzi** [comment]
ok i have pushed this change to the deveop branch

https://github.com/cern-it-sdc-id/puppet-dmlite/commit/9e25491d422f02cb50ea10e60270d9eac1b3f9d3

thanks for your help!
Andrea
