### ISSUE TITLE
lib/facter/dpm-xrootd.rb hammers on the RPM DB

### ISSUE THREAD

**Issue by fschaer** [cern-it-sdc-id/puppet-dmlite#15]
Hello,

The rpm -qa in the exec  in lib/facter/dpm-xrootd.rb is heavily hammering on my small test VMs, and it's run at each facter run.

I'd like to propose a fix : replace the existing with :

> ] rpm -q --queryformat '[%{NAME} %{VERSION}-%{RELEASE}\n]'
> dpm-xrootd dpm-xrootd 3.6.0-1.el6

But this requires another fix in the ruby code, which expects each output line to be following the supplied format, which is not the case on nodes where the package is not installed, or even on the DPM nodes @install time : output then is : 

package dpm-xrootd is not installed

=> the ruby fact has to check the format realy is correct before adding a fact anyways. Should be trivial for a ruby dev...  i.e , not me ;)

Can you fix this ?

**Comment by andrea-manzi** [comment]
so we have to find a Ruby dev around:-)

ok i'll try to see how to change the code
cheers
Andrea

**Comment by fschaer** [comment]
Testing a fix right now :
  version = Facter::Util::Resolution.exec("rpm -q --queryformat '[%{NAME} %{VERSION}-%{RELEASE}\n]' dpm-xrootd|grep -v 'not installed'")

**Comment by andrea-manzi** [comment]
fixed in puppet-dmlite 0.4.4
