### ISSUE TITLE
Multiple LoadModule lines in 00-mpm.conf on CentOS7

### ISSUE THREAD

**Issue by rwf14f** [cern-it-sdc-id/puppet-dmlite#18]
On CentOS7 (puppet stdlib 4.20), the module adds another `LoadModule mpm_event_module modules/mod_mpm_event.so` line to `/etc/httpd/conf.modules.d/00-mpm.conf` with every puppet run.
The problem can be fixed by replacing
`match  => '^#LoadModule mpm_event_module modules/mod_mpm_event.so'`
with
`match  => '^#?LoadModule mpm_event_module modules/mod_mpm_event.so'`
in `manifests/dav/config.pp`.

**Comment by andrea-manzi** [comment]
Hi, 
thanks a lot of reporting this problem!
we are still reccomending to use stdlib 4.15 cause higher versions are not compatible with puppet3 and i cannot reproduce the problem there. Of course we will have to remove this limitation sooner or later as puppet 3 is EOL..
i will test the changes you are proposing also with sdlib  4.15 and if it's ok also there i will release a new version of the module.
cheers
Andrea

**Comment by andrea-manzi** [comment]
it looks ok also with stdlib 4.15, going to release the fix in the next version of the module.
thanks!
Andrea
